apiVersion: v2
name: taskexec
description: Web interface and API for Ansible, Terraform, OpenTofu and scripts
type: application
annotations:
  artifacthub.io/license: Apache-2.0
icon: https://raw.githubusercontent.com/impishMD/TaskExec/develop/web/public/favicon.svg
version: 1.0.2
appVersion: "1.1.0"
kubeVersion: ">=1.26.0-0"
home: https://github.com/impishMD/TaskExec
sources:
  - https://github.com/semaphoreui/charts
  - https://github.com/impishMD/TaskExec
keywords: [ansible, terraform, opentofu, automation]
maintainers:
  - name: impishMD
    url: https://github.com/impishMD
