#!/usr/bin/env bash
set -eo pipefail

echo "---> Gen jeh config"
cat << EOF > /jeh/.dredd/config.json
{
  "dialect": "${JEH_DB_DIALECT}",
  "${JEH_DB_DIALECT}": ${JEH_DB_CONFIG},
  "access_key_encryption": "${JEH_ACCESS_KEY_ENCRYPTION}"
}
EOF

echo "---> Waiting for jeh"
while ! nc -z server 3000; do
  sleep 1
done

echo "---> Start dredd server"
sleep 5
dredd $@
