#!/usr/bin/env bash
set -eo pipefail

echo "---> Gen taskexec config"
cat << EOF > /taskexec/.dredd/config.json
{
  "dialect": "${TASKEXEC_DB_DIALECT}",
  "${TASKEXEC_DB_DIALECT}": ${TASKEXEC_DB_CONFIG},
  "access_key_encryption": "${TASKEXEC_ACCESS_KEY_ENCRYPTION}"
}
EOF

echo "---> Waiting for taskexec"
while ! nc -z server 3000; do
  sleep 1
done

echo "---> Start dredd server"
sleep 5
dredd $@
