version: "3.4"

volumes:
  dredd:

services:
  server:
    environment:
      JEH_ADMIN_PASSWORD: password
      JEH_ADMIN_NAME: Developer
      JEH_ADMIN_EMAIL: admin@localhost
      JEH_ADMIN: admin
      JEH_WEB_ROOT: http://0.0.0.0:3000

  dredd:
    build:
      context: ../../../
      dockerfile: deployment/docker/dredd/Dockerfile
    command:
      - --config
      - .dredd/dredd.docker.yml
    environment:
      JEH_ACCESS_KEY_ENCRYPTION: ${JEH_ACCESS_KEY_ENCRYPTION:-IlRqgrrO5Gp27MlWakDX1xVrPv4jhoUx+ARY+qGyDxQ=}
    volumes:
      - dredd:/data
