version: "3.4"

volumes:
  dredd:

services:
  server:
    environment:
      TASKEXEC_ADMIN_PASSWORD: password
      TASKEXEC_ADMIN_NAME: Developer
      TASKEXEC_ADMIN_EMAIL: admin@localhost
      TASKEXEC_ADMIN: admin
      TASKEXEC_WEB_ROOT: http://0.0.0.0:3000

  dredd:
    build:
      context: ../../../
      dockerfile: deployment/docker/dredd/Dockerfile
    command:
      - --config
      - .dredd/dredd.docker.yml
    environment:
      TASKEXEC_ACCESS_KEY_ENCRYPTION: ${TASKEXEC_ACCESS_KEY_ENCRYPTION:-IlRqgrrO5Gp27MlWakDX1xVrPv4jhoUx+ARY+qGyDxQ=}
    volumes:
      - dredd:/data
