---

name: Question
description: You have a question on how to use JEH
title: "Question: "
labels: ['question', 'triage']

body:
  - type: markdown
    attributes:
      value: |
        Please make sure to go through these steps **before opening an issue**:
        
        - [ ] Read the [documentation](https://github.com/impishMD/jeh/tree/develop/docs/en)
          - [ ] Read the [troubleshooting guide](https://github.com/impishMD/jeh/tree/develop/docs/en)
          - [ ] Read the [documentation regarding manual installations](https://github.com/impishMD/jeh/tree/develop/docs/en) if you did install JEH that way

        - [ ] Check if there are existing [issues](https://github.com/impishMD/jeh/issues) or [discussions](https://github.com/impishMD/jeh/discussions) regarding your topic

  - type: textarea
    id: question
    attributes:
      label: Question
    validations:
      required: true

  - type: dropdown
    id: related-to
    attributes:
      label: Related to
      description: |
        To what parts of JEH is the question related? (if any)

      multiple: true
      options:
        - Web-Frontend (what users interact with)
        - Web-Backend (APIs)
        - Service (scheduled tasks, alerts)
        - Ansible (task execution)
        - Configuration
        - Database
        - Documentation
        - Docker
    validations:
      required: false
