version: "3.4"

volumes:
  mariadb:

services:
  server:
    environment:
      TASKEXEC_DB_DIALECT: mysql
      TASKEXEC_DB_HOST: db
      TASKEXEC_DB_PORT: 3306
      TASKEXEC_DB_USER: ${MARIADB_USERNAME:-taskexec}
      TASKEXEC_DB_PASS: ${MARIADB_PASSWORD:-taskexec}
      TASKEXEC_DB: ${MARIADB_DATABASE:-taskexec}
    depends_on:
      - db

  db:
    image: mariadb:10.8
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT:-root}
      MARIADB_USER: ${MARIADB_USERNAME:-taskexec}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-taskexec}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-taskexec}
    volumes:
      - mariadb:/var/lib/mysql
