version: "3.4"

volumes:
  mariadb:

services:
  server:
    environment:
      JEH_DB_DIALECT: mysql
      JEH_DB_HOST: db
      JEH_DB_PORT: 3306
      JEH_DB_USER: ${MARIADB_USERNAME:-jeh}
      JEH_DB_PASS: ${MARIADB_PASSWORD:-jeh}
      JEH_DB: ${MARIADB_DATABASE:-jeh}
    depends_on:
      - db

  db:
    image: mariadb:10.8
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT:-root}
      MARIADB_USER: ${MARIADB_USERNAME:-jeh}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-jeh}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-jeh}
    volumes:
      - mariadb:/var/lib/mysql
