version: "3.4"

volumes:
  postgres:

services:
  server:
    environment:
      TASKEXEC_DB_DIALECT: postgres
      TASKEXEC_DB_HOST: db
      TASKEXEC_DB_PORT: 5432
      TASKEXEC_DB_USER: ${POSTGRES_USERNAME:-taskexec}
      TASKEXEC_DB_PASS: ${POSTGRES_PASSWORD:-taskexec}
      TASKEXEC_DB: ${POSTGRES_DATABASE:-taskexec}
    depends_on:
      - db

  db:
    image: postgres:14.3
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME:-taskexec}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-taskexec}
      POSTGRES_DB: ${POSTGRES_DATABASE:-taskexec}
    volumes:
      - postgres:/var/lib/postgresql
