#!/bin/sh
set -e
echoerr() { printf "%s\n" "$*" >&2; }

#
# Read environment variables from file if envrionment variable ${1}_FILE is set
#
file_env() {
    local var=""
    local fileVar=""

    eval var="\$${1}"
    eval fileVar="\$${1}_FILE"

    local def="${2:-}"

    if [ -n "${var:-}" ] && [ -n "${fileVar:-}" ]; then
        echo >&2 "error: both ${1} and ${1}_FILE are set (but are exclusive)"
        exit 1
    fi

    local val="$def"

    if [ -n "${var:-}" ]; then
        val="${var}"
    elif [ -n "${fileVar:-}" ]; then
        val="$(cat "${fileVar}")"
    fi

    if [ -n "${val:-}" ]; then
        export "${1}"="$val"
    fi

    unset "${1}_FILE"
}

export JEH_CONFIG_PATH="${JEH_CONFIG_PATH:-/etc/jeh}"
export JEH_DB_PATH="${JEH_DB_PATH:-/var/lib/jeh}"
export JEH_DB_PORT="${JEH_DB_PORT:-}"

file_env 'JEH_DB_USER'
file_env 'JEH_DB_PASS'
file_env 'JEH_ADMIN'
export JEH_ADMIN_EMAIL="${JEH_ADMIN_EMAIL:-admin@localhost}"
export JEH_ADMIN_NAME="${JEH_ADMIN_NAME:-JEH Admin}"
file_env 'JEH_ADMIN_PASSWORD'
export JEH_LDAP_ACTIVATED="${JEH_LDAP_ACTIVATED:-no}"
export JEH_LDAP_HOST="${JEH_LDAP_HOST:-}"
export JEH_LDAP_PORT="${JEH_LDAP_PORT:-}"
export JEH_LDAP_DN_BIND="${JEH_LDAP_DN_BIND:-}"
file_env 'JEH_LDAP_PASSWORD'
export JEH_LDAP_DN_SEARCH="${JEH_LDAP_DN_SEARCH:-}"
export JEH_LDAP_MAPPING_USERNAME="${JEH_LDAP_MAPPING_USERNAME:-uid}"
export JEH_LDAP_MAPPING_FULLNAME="${JEH_LDAP_MAPPING_FULLNAME:-cn}"
export JEH_LDAP_MAPPING_EMAIL="${JEH_LDAP_MAPPING_EMAIL:-mail}"
file_env 'JEH_ACCESS_KEY_ENCRYPTION'


[ -d "${JEH_CONFIG_PATH}" ] || mkdir -p "${JEH_CONFIG_PATH}" || {
    echo "Can't create JEH config path ${JEH_CONFIG_PATH}."
    exit 1
}

[ -d "${JEH_DB_PATH}" ] || mkdir -p "${JEH_DB_PATH}" || {
    echo "Can't create JEH data path ${JEH_DB_PATH}."
    exit 1
}


#
# Extract database host and port from config.json if they are not set.
# Set default JEH_DB_DIALECT and JEH_DB_HOST if empty.
#
if [ -z "${JEH_DB_DIALECT}" ]; then
    if [ -f "${JEH_CONFIG_PATH}/config.json" ]; then
        JEH_DB_DIALECT=$(cat "${JEH_CONFIG_PATH}/config.json" | jq '.dialect // ""' -r)
    fi
fi

export JEH_DB_DIALECT="${JEH_DB_DIALECT:-mysql}"

if [ -z "${JEH_DB_HOST}" ]; then
    if [ -f "${JEH_CONFIG_PATH}/config.json" ]; then
        JEH_DB_HOST=$(cat "${JEH_CONFIG_PATH}/config.json" | jq ".${JEH_DB_DIALECT}.host // \"\"" -r)
    fi
fi

if [ -z "${JEH_DB_HOST}" ]; then
    if [ "${JEH_DB_DIALECT}" = 'sqlite' ]; then
        export JEH_DB_HOST=${JEH_DB_PATH}/database.sqlite
    else
        export JEH_DB_HOST="${JEH_DB_HOST:-0.0.0.0}"
    fi
fi


#
# Remove port number from JEH_DB_HOST and put it to JEH_DB_PORT
#
case "$JEH_DB_HOST" in
  *:*)
    JEH_DB_PORT=$(echo "$JEH_DB_HOST" | cut -d ':' -f 2)
    JEH_DB_HOST=$(echo "$JEH_DB_HOST" | cut -d ':' -f 1)
    ;;
  *)
esac


#
# Set JEH_DB_PORT if it is not set
#
if [ -z "${JEH_DB_PORT}" ]; then
    case ${JEH_DB_DIALECT} in
        mysql)
            JEH_DB_PORT=3306
            ;;
        postgres)
            JEH_DB_PORT=5432
            ;;
        sqlite)
            ;;
        *)
            echoerr "Unknown database dialect: ${JEH_DB_DIALECT}"
            exit 1
            ;;
    esac
fi


#
# Ping database if it is not BoltDB
#
if [ "${JEH_DB_DIALECT}" != 'sqlite' ]; then
    echoerr "Pinging database on ${JEH_DB_HOST} port ${JEH_DB_PORT}..."
    TIMEOUT=30


    while ! $(nc -z "$JEH_DB_HOST" "$JEH_DB_PORT") >/dev/null 2>&1; do
        TIMEOUT=$(expr $TIMEOUT - 1)

        if [ $TIMEOUT -eq 0 ]; then
            echoerr "Could not connect to database server. Exiting."
            exit 1
        fi

        echo -n "."
        sleep 1
    done
    
    export JEH_DB_HOST="${JEH_DB_HOST}:${JEH_DB_PORT}"
fi


#
# Generate new config.json if it does not exist
#
JEH_FIRST_RUN=no
if [ ! -f "${JEH_CONFIG_PATH}/config.json" ]; then
    JEH_FIRST_RUN=yes
    echoerr "Generating setup file ${TMP_STDIN_CONFIG_FILE} ..."

    TMP_STDIN_CONFIG_FILE=$(mktemp)


    JEH_TMP_PATH=${JEH_TMP_PATH:-/tmp/jeh}
    [ -d "${JEH_TMP_PATH}" ] || mkdir -p "${JEH_TMP_PATH}" || {
        echo "Can't create JEH tmp path ${JEH_TMP_PATH}."
        exit 1
    }


    case ${JEH_DB_DIALECT} in
        mysql)
            JEH_DB_DIALECT_ID=1
            ;;
        postgres)
            JEH_DB_DIALECT_ID=3
            ;;
        sqlite)
            JEH_DB_DIALECT_ID=4
            ;;
        *)
            echoerr "Unknown database dialect: ${JEH_DB_DIALECT}"
            exit 1
            ;;
    esac


    cat << EOF > "${TMP_STDIN_CONFIG_FILE}"
${JEH_DB_DIALECT_ID}
EOF

    if [ "${JEH_DB_DIALECT}" = "sqlite" ]; then
        cat << EOF >> "${TMP_STDIN_CONFIG_FILE}"
${JEH_DB_HOST}
EOF
    else
        cat << EOF >> "${TMP_STDIN_CONFIG_FILE}"
${JEH_DB_HOST}
${JEH_DB_USER}
${JEH_DB_PASS}
${JEH_DB:-jeh}
EOF
    fi

    cat << EOF >> "${TMP_STDIN_CONFIG_FILE}"
${JEH_TMP_PATH}
${JEH_WEB_ROOT:-}
no
no
no
no
no
${JEH_LDAP_ACTIVATED}
EOF

    if [ "${JEH_LDAP_ACTIVATED}" = "yes" ]; then
        cat << EOF >> "${TMP_STDIN_CONFIG_FILE}"
${JEH_LDAP_HOST}:${JEH_LDAP_PORT}
${JEH_LDAP_NEEDTLS:-no}
${JEH_LDAP_DN_BIND}
${JEH_LDAP_PASSWORD}
${JEH_LDAP_DN_SEARCH}
${JEH_LDAP_SEARCH_FILTER:-(uid=%s)}
${JEH_LDAP_MAPPING_DN:-dn}
${JEH_LDAP_MAPPING_USERNAME}
${JEH_LDAP_MAPPING_FULLNAME}
${JEH_LDAP_MAPPING_EMAIL}
EOF
    fi;

    cat << EOF >> "${TMP_STDIN_CONFIG_FILE}"
${JEH_CONFIG_PATH}
${JEH_ADMIN}
${JEH_ADMIN_EMAIL}
${JEH_ADMIN_NAME}
${JEH_ADMIN_PASSWORD}
EOF


    echoerr "Executing jeh setup"
    if test "$#" -ne 1; then
        /usr/local/bin/jeh setup - < "${TMP_STDIN_CONFIG_FILE}"
    else
        "$1" setup - < "${TMP_STDIN_CONFIG_FILE}"
    fi

    rm -f "${TMP_STDIN_CONFIG_FILE}"
fi

#
# Install additional python dependencies
#
if test -f "${JEH_CONFIG_PATH}/requirements.txt"; then
    echoerr "Installing additional python dependencies"
    pip3 install --upgrade \
        -r "${JEH_CONFIG_PATH}/requirements.txt"
else
    echoerr "No additional python dependencies to install"
fi

#
# Migrate from BoltDB if JEH_MIGRATE_FROM_BOLTDB is set (first run only, SQLite only, skipped if DB file already exists)
#
case "${JEH_MIGRATE_FROM_BOLTDB:-}" in
    [Tt][Rr][Uu][Ee]|[Yy][Ee][Ss])
        JEH_MIGRATE_FROM_BOLTDB="${JEH_DB_PATH}/database.boltdb"
        ;;
esac

if [ -n "${JEH_MIGRATE_FROM_BOLTDB:-}" ] && [ "${JEH_FIRST_RUN}" = "yes" ]; then
    if [ "${JEH_DB_DIALECT}" != "sqlite" ]; then
        echoerr "JEH_MIGRATE_FROM_BOLTDB is only supported with SQLite dialect, ignoring"
    else
        echoerr "Migrating from BoltDB: ${JEH_MIGRATE_FROM_BOLTDB}"
        MIGRATE_ARGS="--from-boltdb=${JEH_MIGRATE_FROM_BOLTDB} --merge-existing-users"
        if [ -n "${JEH_MIGRATE_SKIP_TASK_OUTPUT:-}" ]; then
            MIGRATE_ARGS="${MIGRATE_ARGS} --skip-task-output"
        fi
        if test "$#" -ne 1; then
            /usr/local/bin/jeh migrate ${MIGRATE_ARGS} --config "${JEH_CONFIG_PATH}/config.json"
        else
            "$1" migrate ${MIGRATE_ARGS} --config "${JEH_CONFIG_PATH}/config.json"
        fi
    fi
fi

# Import project if environment variable JEH_IMPORT_PROJECT_FILE is defined.
# Optionally use JEH_IMPORT_PROJECT_NAME to specify the project name.
if [ -n "${JEH_IMPORT_PROJECT_FILE:-}" ] && [ "${JEH_FIRST_RUN}" = "yes" ]; then
    echoerr "Importing project from ${JEH_IMPORT_PROJECT_FILE}"
    IMPORT_ARGS="--file ${JEH_IMPORT_PROJECT_FILE}"
    if [ -n "${JEH_IMPORT_PROJECT_NAME:-}" ]; then
        echoerr "Using project name: ${JEH_IMPORT_PROJECT_NAME}"
        IMPORT_ARGS="${IMPORT_ARGS} --project-name ${JEH_IMPORT_PROJECT_NAME}"
    fi
    if test "$#" -ne 1; then
        /usr/local/bin/jeh project import ${IMPORT_ARGS} --config "${JEH_CONFIG_PATH}/config.json" || echoerr "Project import failed"
    else
        "$1" project import ${IMPORT_ARGS} || echoerr "Project import failed"
    fi
fi


#
# Start JEH server
#
echoerr "Starting jeh server"
if test "$#" -ne 1; then
    exec /usr/local/bin/jeh server --config "${JEH_CONFIG_PATH}/config.json"
else
    exec "$@"
fi
