#!/bin/sh
set -e
echoerr() { printf "%s\n" "$*" >&2; }

#
# Read environment variables from file if envrionment variable ${1}_FILE is set
#
file_env() {
    local var=""
    local fileVar=""

    eval var="\$${1}"
    eval fileVar="\$${1}_FILE"

    local def="${2:-}"

    if [ -n "${var:-}" ] && [ -n "${fileVar:-}" ]; then
        echo >&2 "error: both ${1} and ${1}_FILE are set (but are exclusive)"
        exit 1
    fi

    local val="$def"

    if [ -n "${var:-}" ]; then
        val="${var}"
    elif [ -n "${fileVar:-}" ]; then
        val="$(cat "${fileVar}")"
    fi

    if [ -n "${val:-}" ]; then
        export "${1}"="$val"
    fi

    unset "${1}_FILE"
}

export TASKEXEC_CONFIG_PATH="${TASKEXEC_CONFIG_PATH:-/etc/taskexec}"
export TASKEXEC_DB_PATH="${TASKEXEC_DB_PATH:-/var/lib/taskexec}"
export TASKEXEC_DB_PORT="${TASKEXEC_DB_PORT:-}"

file_env 'TASKEXEC_DB_USER'
file_env 'TASKEXEC_DB_PASS'
file_env 'TASKEXEC_ADMIN'
export TASKEXEC_ADMIN_EMAIL="${TASKEXEC_ADMIN_EMAIL:-admin@localhost}"
export TASKEXEC_ADMIN_NAME="${TASKEXEC_ADMIN_NAME:-TaskExec Admin}"
file_env 'TASKEXEC_ADMIN_PASSWORD'
export TASKEXEC_LDAP_ACTIVATED="${TASKEXEC_LDAP_ACTIVATED:-no}"
export TASKEXEC_LDAP_HOST="${TASKEXEC_LDAP_HOST:-}"
export TASKEXEC_LDAP_PORT="${TASKEXEC_LDAP_PORT:-}"
export TASKEXEC_LDAP_DN_BIND="${TASKEXEC_LDAP_DN_BIND:-}"
file_env 'TASKEXEC_LDAP_PASSWORD'
export TASKEXEC_LDAP_DN_SEARCH="${TASKEXEC_LDAP_DN_SEARCH:-}"
export TASKEXEC_LDAP_MAPPING_USERNAME="${TASKEXEC_LDAP_MAPPING_USERNAME:-uid}"
export TASKEXEC_LDAP_MAPPING_FULLNAME="${TASKEXEC_LDAP_MAPPING_FULLNAME:-cn}"
export TASKEXEC_LDAP_MAPPING_EMAIL="${TASKEXEC_LDAP_MAPPING_EMAIL:-mail}"
file_env 'TASKEXEC_ACCESS_KEY_ENCRYPTION'


[ -d "${TASKEXEC_CONFIG_PATH}" ] || mkdir -p "${TASKEXEC_CONFIG_PATH}" || {
    echo "Can't create TaskExec config path ${TASKEXEC_CONFIG_PATH}."
    exit 1
}

[ -d "${TASKEXEC_DB_PATH}" ] || mkdir -p "${TASKEXEC_DB_PATH}" || {
    echo "Can't create TaskExec data path ${TASKEXEC_DB_PATH}."
    exit 1
}


#
# Extract database host and port from config.json if they are not set.
# Set default TASKEXEC_DB_DIALECT and TASKEXEC_DB_HOST if empty.
#
if [ -z "${TASKEXEC_DB_DIALECT}" ]; then
    if [ -f "${TASKEXEC_CONFIG_PATH}/config.json" ]; then
        TASKEXEC_DB_DIALECT=$(cat "${TASKEXEC_CONFIG_PATH}/config.json" | jq '.dialect // ""' -r)
    fi
fi

export TASKEXEC_DB_DIALECT="${TASKEXEC_DB_DIALECT:-mysql}"

if [ -z "${TASKEXEC_DB_HOST}" ]; then
    if [ -f "${TASKEXEC_CONFIG_PATH}/config.json" ]; then
        TASKEXEC_DB_HOST=$(cat "${TASKEXEC_CONFIG_PATH}/config.json" | jq ".${TASKEXEC_DB_DIALECT}.host // \"\"" -r)
    fi
fi

if [ -z "${TASKEXEC_DB_HOST}" ]; then
    if [ "${TASKEXEC_DB_DIALECT}" = 'sqlite' ]; then
        export TASKEXEC_DB_HOST=${TASKEXEC_DB_PATH}/database.sqlite
    else
        export TASKEXEC_DB_HOST="${TASKEXEC_DB_HOST:-0.0.0.0}"
    fi
fi


#
# Remove port number from TASKEXEC_DB_HOST and put it to TASKEXEC_DB_PORT
#
case "$TASKEXEC_DB_HOST" in
  *:*)
    TASKEXEC_DB_PORT=$(echo "$TASKEXEC_DB_HOST" | cut -d ':' -f 2)
    TASKEXEC_DB_HOST=$(echo "$TASKEXEC_DB_HOST" | cut -d ':' -f 1)
    ;;
  *)
esac


#
# Set TASKEXEC_DB_PORT if it is not set
#
if [ -z "${TASKEXEC_DB_PORT}" ]; then
    case ${TASKEXEC_DB_DIALECT} in
        mysql)
            TASKEXEC_DB_PORT=3306
            ;;
        postgres)
            TASKEXEC_DB_PORT=5432
            ;;
        sqlite)
            ;;
        *)
            echoerr "Unknown database dialect: ${TASKEXEC_DB_DIALECT}"
            exit 1
            ;;
    esac
fi


#
# Ping database if it is not BoltDB
#
if [ "${TASKEXEC_DB_DIALECT}" != 'sqlite' ]; then
    echoerr "Pinging database on ${TASKEXEC_DB_HOST} port ${TASKEXEC_DB_PORT}..."
    TIMEOUT=30


    while ! $(nc -z "$TASKEXEC_DB_HOST" "$TASKEXEC_DB_PORT") >/dev/null 2>&1; do
        TIMEOUT=$(expr $TIMEOUT - 1)

        if [ $TIMEOUT -eq 0 ]; then
            echoerr "Could not connect to database server. Exiting."
            exit 1
        fi

        echo -n "."
        sleep 1
    done
    
    export TASKEXEC_DB_HOST="${TASKEXEC_DB_HOST}:${TASKEXEC_DB_PORT}"
fi


#
# Generate new config.json if it does not exist
#
TASKEXEC_FIRST_RUN=no
if [ ! -f "${TASKEXEC_CONFIG_PATH}/config.json" ]; then
    TASKEXEC_FIRST_RUN=yes
    echoerr "Generating setup file ${TMP_STDIN_CONFIG_FILE} ..."

    TMP_STDIN_CONFIG_FILE=$(mktemp)


    TASKEXEC_TMP_PATH=${TASKEXEC_TMP_PATH:-/tmp/taskexec}
    [ -d "${TASKEXEC_TMP_PATH}" ] || mkdir -p "${TASKEXEC_TMP_PATH}" || {
        echo "Can't create TaskExec tmp path ${TASKEXEC_TMP_PATH}."
        exit 1
    }


    case ${TASKEXEC_DB_DIALECT} in
        mysql)
            TASKEXEC_DB_DIALECT_ID=1
            ;;
        postgres)
            TASKEXEC_DB_DIALECT_ID=3
            ;;
        sqlite)
            TASKEXEC_DB_DIALECT_ID=4
            ;;
        *)
            echoerr "Unknown database dialect: ${TASKEXEC_DB_DIALECT}"
            exit 1
            ;;
    esac


    cat << EOF > "${TMP_STDIN_CONFIG_FILE}"
${TASKEXEC_DB_DIALECT_ID}
EOF

    if [ "${TASKEXEC_DB_DIALECT}" = "sqlite" ]; then
        cat << EOF >> "${TMP_STDIN_CONFIG_FILE}"
${TASKEXEC_DB_HOST}
EOF
    else
        cat << EOF >> "${TMP_STDIN_CONFIG_FILE}"
${TASKEXEC_DB_HOST}
${TASKEXEC_DB_USER}
${TASKEXEC_DB_PASS}
${TASKEXEC_DB:-taskexec}
EOF
    fi

    cat << EOF >> "${TMP_STDIN_CONFIG_FILE}"
${TASKEXEC_TMP_PATH}
${TASKEXEC_WEB_ROOT:-}
no
no
no
no
${TASKEXEC_LDAP_ACTIVATED}
EOF

    if [ "${TASKEXEC_LDAP_ACTIVATED}" = "yes" ]; then
        cat << EOF >> "${TMP_STDIN_CONFIG_FILE}"
${TASKEXEC_LDAP_HOST}:${TASKEXEC_LDAP_PORT}
${TASKEXEC_LDAP_NEEDTLS:-no}
${TASKEXEC_LDAP_DN_BIND}
${TASKEXEC_LDAP_PASSWORD}
${TASKEXEC_LDAP_DN_SEARCH}
${TASKEXEC_LDAP_SEARCH_FILTER:-(uid=%s)}
${TASKEXEC_LDAP_MAPPING_DN:-dn}
${TASKEXEC_LDAP_MAPPING_USERNAME}
${TASKEXEC_LDAP_MAPPING_FULLNAME}
${TASKEXEC_LDAP_MAPPING_EMAIL}
EOF
    fi;

    cat << EOF >> "${TMP_STDIN_CONFIG_FILE}"
${TASKEXEC_CONFIG_PATH}
${TASKEXEC_ADMIN}
${TASKEXEC_ADMIN_EMAIL}
${TASKEXEC_ADMIN_NAME}
${TASKEXEC_ADMIN_PASSWORD}
EOF


    echoerr "Executing taskexec setup"
    if test "$#" -ne 1; then
        /usr/local/bin/taskexec setup - < "${TMP_STDIN_CONFIG_FILE}"
    else
        "$1" setup - < "${TMP_STDIN_CONFIG_FILE}"
    fi

    rm -f "${TMP_STDIN_CONFIG_FILE}"
fi

#
# Install additional python dependencies
#
if test -f "${TASKEXEC_CONFIG_PATH}/requirements.txt"; then
    echoerr "Installing additional python dependencies"
    pip3 install --upgrade \
        -r "${TASKEXEC_CONFIG_PATH}/requirements.txt"
else
    echoerr "No additional python dependencies to install"
fi

#
# Migrate from BoltDB if TASKEXEC_MIGRATE_FROM_BOLTDB is set (first run only, SQLite only, skipped if DB file already exists)
#
case "${TASKEXEC_MIGRATE_FROM_BOLTDB:-}" in
    [Tt][Rr][Uu][Ee]|[Yy][Ee][Ss])
        TASKEXEC_MIGRATE_FROM_BOLTDB="${TASKEXEC_DB_PATH}/database.boltdb"
        ;;
esac

if [ -n "${TASKEXEC_MIGRATE_FROM_BOLTDB:-}" ] && [ "${TASKEXEC_FIRST_RUN}" = "yes" ]; then
    if [ "${TASKEXEC_DB_DIALECT}" != "sqlite" ]; then
        echoerr "TASKEXEC_MIGRATE_FROM_BOLTDB is only supported with SQLite dialect, ignoring"
    else
        echoerr "Migrating from BoltDB: ${TASKEXEC_MIGRATE_FROM_BOLTDB}"
        MIGRATE_ARGS="--from-boltdb=${TASKEXEC_MIGRATE_FROM_BOLTDB} --merge-existing-users"
        if [ -n "${TASKEXEC_MIGRATE_SKIP_TASK_OUTPUT:-}" ]; then
            MIGRATE_ARGS="${MIGRATE_ARGS} --skip-task-output"
        fi
        if test "$#" -ne 1; then
            /usr/local/bin/taskexec migrate ${MIGRATE_ARGS} --config "${TASKEXEC_CONFIG_PATH}/config.json"
        else
            "$1" migrate ${MIGRATE_ARGS} --config "${TASKEXEC_CONFIG_PATH}/config.json"
        fi
    fi
fi

# Import project if environment variable TASKEXEC_IMPORT_PROJECT_FILE is defined.
# Optionally use TASKEXEC_IMPORT_PROJECT_NAME to specify the project name.
if [ -n "${TASKEXEC_IMPORT_PROJECT_FILE:-}" ] && [ "${TASKEXEC_FIRST_RUN}" = "yes" ]; then
    echoerr "Importing project from ${TASKEXEC_IMPORT_PROJECT_FILE}"
    IMPORT_ARGS="--file ${TASKEXEC_IMPORT_PROJECT_FILE}"
    if [ -n "${TASKEXEC_IMPORT_PROJECT_NAME:-}" ]; then
        echoerr "Using project name: ${TASKEXEC_IMPORT_PROJECT_NAME}"
        IMPORT_ARGS="${IMPORT_ARGS} --project-name ${TASKEXEC_IMPORT_PROJECT_NAME}"
    fi
    if test "$#" -ne 1; then
        /usr/local/bin/taskexec project import ${IMPORT_ARGS} --config "${TASKEXEC_CONFIG_PATH}/config.json" || echoerr "Project import failed"
    else
        "$1" project import ${IMPORT_ARGS} || echoerr "Project import failed"
    fi
fi


#
# Start TaskExec server
#
echoerr "Starting taskexec server"
if test "$#" -ne 1; then
    exec /usr/local/bin/taskexec server --config "${TASKEXEC_CONFIG_PATH}/config.json"
else
    exec "$@"
fi
