version: "3.4"

services:
  runner:
    image: docker.io/impishmd/taskexec:${TASKEXEC_VERSION:-latest}-runner
    restart: always
    environment:
      TASKEXEC_WEB_ROOT: ${TASKEXEC_WEB_ROOT:-http://server:3000}
      TASKEXEC_RUNNER_API_URL: ${TASKEXEC_RUNNER_API_URL:-http://server:3000/internal}
      TASKEXEC_RUNNER_REGISTRATION_TOKEN: ${TASKEXEC_RUNNER_REGISTRATION_TOKEN:-H1wDyorbg6gTSwJlVwle2Fne}

  server:
    environment:
      TASKEXEC_RUNNER_REGISTRATION_TOKEN: ${TASKEXEC_RUNNER_REGISTRATION_TOKEN:-H1wDyorbg6gTSwJlVwle2Fne}
