version: "3.4"

volumes:
  server:

services:
  server:
    image: docker.io/impishmd/jeh:${JEH_VERSION:-latest}
    restart: always
    environment:
      JEH_ADMIN_NAME: ${JEH_ADMIN_NAME:-Admin}
      JEH_ADMIN: ${JEH_ADMIN_USERNAME:-admin}
      JEH_ADMIN_PASSWORD: ${JEH_ADMIN_PASSWORD:-p455w0rd}
      JEH_ADMIN_EMAIL: ${JEH_ADMIN_EMAIL:-admin@localhost}
      JEH_WEB_ROOT: ${JEH_WEB_ROOT:-http://0.0.0.0:3000}
      JEH_ACCESS_KEY_ENCRYPTION: ${JEH_ACCESS_KEY_ENCRYPTION:-IlRqgrrO5Gp27MlWakDX1xVrPv4jhoUx+ARY+qGyDxQ=}
    volumes:
      - server:/var/lib/jeh
    ports:
      - "3000:3000"
