version: "3.4"

volumes:
  server:

services:
  server:
    image: docker.io/impishmd/taskexec:${TASKEXEC_VERSION:-latest}
    restart: always
    environment:
      TASKEXEC_ADMIN_NAME: ${TASKEXEC_ADMIN_NAME:-Admin}
      TASKEXEC_ADMIN: ${TASKEXEC_ADMIN_USERNAME:-admin}
      TASKEXEC_ADMIN_PASSWORD: ${TASKEXEC_ADMIN_PASSWORD:-p455w0rd}
      TASKEXEC_ADMIN_EMAIL: ${TASKEXEC_ADMIN_EMAIL:-admin@localhost}
      TASKEXEC_WEB_ROOT: ${TASKEXEC_WEB_ROOT:-http://0.0.0.0:3000}
      TASKEXEC_ACCESS_KEY_ENCRYPTION: ${TASKEXEC_ACCESS_KEY_ENCRYPTION:-IlRqgrrO5Gp27MlWakDX1xVrPv4jhoUx+ARY+qGyDxQ=}
    volumes:
      - server:/var/lib/taskexec
    ports:
      - "3000:3000"
