#!/bin/sh
set -e
echoerr() { printf "%s\n" "$*" >&2; }

export JEH_CONFIG_PATH="${JEH_CONFIG_PATH:-/etc/jeh}"
export JEH_TMP_PATH="${JEH_TMP_PATH:-/tmp/jeh}"
export JEH_DATA_PATH="${JEH_DATA_PATH:-/var/lib/jeh}"

if test -f "${JEH_CONFIG_PATH}/requirements.txt"; then
    echoerr "Installing additional python dependencies"
    pip3 install --upgrade -r "${JEH_CONFIG_PATH}/requirements.txt"
else
    echoerr "No additional python dependencies to install"
fi

echoerr "Starting jeh runner"

RUNNER_CMD="/usr/local/bin/jeh runner start --no-config"

if [ -n "${JEH_RUNNER_REGISTRATION_TOKEN:-}" ] || [ -n "${JEH_RUNNER_REGISTRATION_TOKEN_FILE:-}" ]; then
  if [ -z "${JEH_RUNNER_TOKEN:-}" ] && [ -z "${JEH_RUNNER_TOKEN_FILE:-}" ]; then
    export JEH_RUNNER_TOKEN_FILE="${JEH_DATA_PATH}/runner_token.txt"
  fi
  echoerr "Registration token provided, starting runner in registration mode"
  exec ${RUNNER_CMD} --register
else
  exec ${RUNNER_CMD}
fi
