#!/bin/sh
set -e
echoerr() { printf "%s\n" "$*" >&2; }

export TASKEXEC_CONFIG_PATH="${TASKEXEC_CONFIG_PATH:-/etc/taskexec}"
export TASKEXEC_TMP_PATH="${TASKEXEC_TMP_PATH:-/tmp/taskexec}"
export TASKEXEC_DATA_PATH="${TASKEXEC_DATA_PATH:-/var/lib/taskexec}"

if test -f "${TASKEXEC_CONFIG_PATH}/requirements.txt"; then
    echoerr "Installing additional python dependencies"
    pip3 install --upgrade -r "${TASKEXEC_CONFIG_PATH}/requirements.txt"
else
    echoerr "No additional python dependencies to install"
fi

echoerr "Starting taskexec runner"

RUNNER_CMD="/usr/local/bin/taskexec runner start --no-config"

if [ -n "${TASKEXEC_RUNNER_REGISTRATION_TOKEN:-}" ] || [ -n "${TASKEXEC_RUNNER_REGISTRATION_TOKEN_FILE:-}" ]; then
  if [ -z "${TASKEXEC_RUNNER_TOKEN:-}" ] && [ -z "${TASKEXEC_RUNNER_TOKEN_FILE:-}" ]; then
    export TASKEXEC_RUNNER_TOKEN_FILE="${TASKEXEC_DATA_PATH}/runner_token.txt"
  fi
  echoerr "Registration token provided, starting runner in registration mode"
  exec ${RUNNER_CMD} --register
else
  exec ${RUNNER_CMD}
fi
